/**
 * Idempotent schema statements, mirroring src/db/schema.ts exactly.
 * Used by ensureDatabase() so the app can recreate its tables on any
 * fresh/missing/corrupt database without needing `drizzle-kit push`.
 */
export const DDL: string[] = [
  `CREATE TABLE IF NOT EXISTS "users" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL UNIQUE,
  "role" TEXT NOT NULL DEFAULT 'student',
  "roll_no_or_emp_id" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "semester" INTEGER,
  "designation" TEXT,
  "phone" TEXT,
  "avatar_url" TEXT,
  "gpa" TEXT,
  "status" TEXT NOT NULL DEFAULT 'active',
  "password_hash" TEXT NOT NULL DEFAULT '',
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "sessions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "token" TEXT NOT NULL UNIQUE,
  "user_id" INTEGER NOT NULL,
  "expires_at" INTEGER NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "departments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "code" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "head_of_department" TEXT NOT NULL,
  "location" TEXT,
  "student_count" INTEGER DEFAULT 0,
  "faculty_count" INTEGER DEFAULT 0
);`,
  `CREATE TABLE IF NOT EXISTS "courses" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "code" TEXT NOT NULL UNIQUE,
  "name" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "credits" INTEGER NOT NULL DEFAULT 3,
  "semester" INTEGER NOT NULL DEFAULT 1,
  "faculty_id" INTEGER,
  "faculty_name" TEXT,
  "room" TEXT,
  "schedule" TEXT,
  "description" TEXT
);`,
  `CREATE TABLE IF NOT EXISTS "attendance" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "course_id" INTEGER NOT NULL,
  "course_code" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "status" TEXT NOT NULL,
  "period" TEXT DEFAULT 'Lecture 1',
  "marked_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "grades" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "course_id" INTEGER NOT NULL,
  "course_name" TEXT NOT NULL,
  "exam_type" TEXT NOT NULL,
  "marks_obtained" TEXT NOT NULL,
  "max_marks" TEXT NOT NULL DEFAULT '100',
  "grade_letter" TEXT NOT NULL,
  "semester" INTEGER NOT NULL DEFAULT 1,
  "remarks" TEXT,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "fee_records" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "roll_no" TEXT NOT NULL,
  "fee_type" TEXT NOT NULL,
  "amount" TEXT NOT NULL,
  "due_date" TEXT NOT NULL,
  "paid_date" TEXT,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "receipt_number" TEXT,
  "payment_method" TEXT,
  "course_code" TEXT,
  "course_name" TEXT,
  "semester" INTEGER,
  "paid_amount" TEXT NOT NULL DEFAULT '0',
  "collected_by" TEXT,
  "collected_at" TEXT,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "fee_structures" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "course_code" TEXT NOT NULL,
  "course_name" TEXT NOT NULL,
  "semester" INTEGER NOT NULL,
  "fee_type" TEXT NOT NULL,
  "amount" TEXT NOT NULL,
  "due_date" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "fee_payments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "fee_record_id" INTEGER NOT NULL,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "amount" TEXT NOT NULL,
  "payment_method" TEXT NOT NULL,
  "receipt_number" TEXT NOT NULL,
  "paid_at" TEXT NOT NULL,
  "collected_by" TEXT,
  "collected_by_id" INTEGER,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "assignments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "course_id" INTEGER NOT NULL,
  "course_name" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "due_date" TEXT NOT NULL,
  "max_marks" INTEGER NOT NULL DEFAULT 100,
  "faculty_name" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "assignment_submissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "assignment_id" INTEGER NOT NULL,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "submission_text" TEXT,
  "file_url" TEXT,
  "status" TEXT NOT NULL DEFAULT 'submitted',
  "marks" TEXT,
  "feedback" TEXT,
  "submitted_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "notices" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "title" TEXT NOT NULL,
  "content" TEXT NOT NULL,
  "category" TEXT NOT NULL DEFAULT 'Academic',
  "priority" TEXT NOT NULL DEFAULT 'normal',
  "author_name" TEXT NOT NULL DEFAULT 'Administration Office',
  "published_date" TEXT NOT NULL,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "leave_requests" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "roll_no" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "from_date" TEXT NOT NULL,
  "to_date" TEXT NOT NULL,
  "reason" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "reviewed_by" TEXT,
  "reviewed_at" TEXT,
  "remarks" TEXT,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "timetable" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "course_code" TEXT NOT NULL,
  "course_name" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "semester" INTEGER NOT NULL,
  "day_of_week" TEXT NOT NULL,
  "start_time" TEXT NOT NULL,
  "end_time" TEXT NOT NULL,
  "room" TEXT NOT NULL,
  "faculty_name" TEXT NOT NULL
);`,
  `CREATE TABLE IF NOT EXISTS "admissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student_id" INTEGER NOT NULL UNIQUE,
  "admission_number" TEXT NOT NULL,
  "admission_date" TEXT NOT NULL,
  "category" TEXT NOT NULL DEFAULT 'General',
  "previous_institution" TEXT,
  "father_name" TEXT,
  "mother_name" TEXT,
  "guardian_phone" TEXT,
  "blood_group" TEXT,
  "address" TEXT,
  "is_hosteler" INTEGER NOT NULL DEFAULT 0,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "documents" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "category" TEXT NOT NULL DEFAULT 'Other',
  "file_name" TEXT NOT NULL,
  "mime_type" TEXT NOT NULL DEFAULT 'application/octet-stream',
  "file_size" INTEGER NOT NULL DEFAULT 0,
  "data" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'pending',
  "uploaded_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "enrollments" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "course_id" INTEGER NOT NULL,
  "course_code" TEXT NOT NULL,
  "course_name" TEXT NOT NULL,
  "semester" INTEGER NOT NULL DEFAULT 1,
  "status" TEXT NOT NULL DEFAULT 'active'
);`,
  `CREATE TABLE IF NOT EXISTS "sections" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "code" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "semester" INTEGER NOT NULL DEFAULT 1,
  "room" TEXT
);`,
  `CREATE TABLE IF NOT EXISTS "semesters" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "number" INTEGER NOT NULL,
  "name" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'inactive',
  "starts_on" TEXT,
  "ends_on" TEXT
);`,
  `CREATE TABLE IF NOT EXISTS "academic_sessions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL UNIQUE,
  "start_date" TEXT NOT NULL,
  "end_date" TEXT NOT NULL,
  "is_current" INTEGER NOT NULL DEFAULT 0
);`,
  `CREATE TABLE IF NOT EXISTS "exam_schedules" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "exam_type" TEXT NOT NULL,
  "course_code" TEXT NOT NULL,
  "course_name" TEXT NOT NULL,
  "department" TEXT NOT NULL,
  "semester" INTEGER NOT NULL DEFAULT 1,
  "exam_date" TEXT NOT NULL,
  "start_time" TEXT NOT NULL,
  "end_time" TEXT NOT NULL,
  "room" TEXT NOT NULL
);`,
  `CREATE TABLE IF NOT EXISTS "exams" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "name" TEXT NOT NULL,
  "exam_type" TEXT NOT NULL DEFAULT 'Mid-Term',
  "department" TEXT NOT NULL,
  "semester" INTEGER NOT NULL DEFAULT 1,
  "session" TEXT NOT NULL DEFAULT '2025-26',
  "start_date" TEXT NOT NULL,
  "end_date" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'scheduled',
  "passing_percent" INTEGER NOT NULL DEFAULT 40,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "internal_marks" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "student_id" INTEGER NOT NULL,
  "student_name" TEXT NOT NULL,
  "course_id" INTEGER NOT NULL,
  "course_code" TEXT NOT NULL,
  "course_name" TEXT NOT NULL,
  "exam_type" TEXT NOT NULL,
  "semester" INTEGER NOT NULL DEFAULT 1,
  "theory_marks" TEXT NOT NULL DEFAULT '0',
  "practical_marks" TEXT NOT NULL DEFAULT '0',
  "max_theory" TEXT NOT NULL DEFAULT '30',
  "max_practical" TEXT NOT NULL DEFAULT '20',
  "total_marks" TEXT NOT NULL,
  "max_total" TEXT NOT NULL,
  "pass_marks" TEXT NOT NULL,
  "grade_letter" TEXT NOT NULL,
  "result" TEXT NOT NULL DEFAULT 'pass',
  "status" TEXT NOT NULL DEFAULT 'draft',
  "remarks" TEXT,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
  `CREATE TABLE IF NOT EXISTS "permissions" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "role" TEXT NOT NULL,
  "module" TEXT NOT NULL,
  "can_view" INTEGER NOT NULL DEFAULT 1,
  "can_create" INTEGER NOT NULL DEFAULT 0,
  "can_edit" INTEGER NOT NULL DEFAULT 0,
  "can_delete" INTEGER NOT NULL DEFAULT 0
);`,
  `CREATE TABLE IF NOT EXISTS "faculty_attendance" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "faculty_id" INTEGER NOT NULL,
  "faculty_name" TEXT NOT NULL,
  "date" TEXT NOT NULL,
  "status" TEXT NOT NULL DEFAULT 'present',
  "marked_by" TEXT,
  "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);`,
];
