import { sql } from "drizzle-orm";
import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

const id = () => integer("id").primaryKey({ autoIncrement: true });
const createdAt = (name = "created_at") => text(name).default(sql`CURRENT_TIMESTAMP`).notNull();

export const students = sqliteTable("students", {
  id: id(), name: text("name").notNull(), email: text("email").notNull().unique(), rollNo: text("roll_no").notNull().unique(), department: text("department").notNull(), semester: integer("semester").default(1), phone: text("phone"), avatarUrl: text("avatar_url"), gpa: text("gpa").default("0.00"), status: text("status").notNull().default("active"), passwordHash: text("password_hash").notNull().default(""), createdAt: createdAt(),
});
export const faculty = sqliteTable("faculty", {
  id: id(), name: text("name").notNull(), email: text("email").notNull().unique(), empId: text("emp_id").notNull().unique(), department: text("department").notNull(), subRole: text("sub_role").notNull().default("teacher"), designation: text("designation").notNull().default("Assistant Professor"), phone: text("phone"), avatarUrl: text("avatar_url"), status: text("status").notNull().default("active"), passwordHash: text("password_hash").notNull().default(""), createdAt: createdAt(),
});
export const admins = sqliteTable("admins", {
  id: id(), name: text("name").notNull(), email: text("email").notNull().unique(), empId: text("emp_id").notNull().unique(), department: text("department").notNull().default("Administration"), designation: text("designation").notNull().default("System Administrator"), phone: text("phone"), avatarUrl: text("avatar_url"), status: text("status").notNull().default("active"), passwordHash: text("password_hash").notNull().default(""), createdAt: createdAt(),
});
export const sessions = sqliteTable("sessions", { id: id(), token: text("token").notNull().unique(), userId: integer("user_id").notNull(), userRole: text("user_role").notNull().default("student"), expiresAt: integer("expires_at").notNull(), createdAt: createdAt() });
export const departments = sqliteTable("departments", { id: id(), code: text("code").notNull().unique(), name: text("name").notNull(), headOfDepartment: text("head_of_department").notNull(), location: text("location"), studentCount: integer("student_count").default(0), facultyCount: integer("faculty_count").default(0) });
export const courses = sqliteTable("courses", { id: id(), code: text("code").notNull().unique(), name: text("name").notNull(), department: text("department").notNull(), credits: integer("credits").notNull().default(3), semester: integer("semester").notNull().default(1), facultyId: integer("faculty_id"), facultyName: text("faculty_name"), room: text("room"), schedule: text("schedule"), description: text("description") });
export const attendance = sqliteTable("attendance", { id: id(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), courseId: integer("course_id").notNull(), courseCode: text("course_code").notNull(), date: text("date").notNull(), status: text("status").notNull(), period: text("period").default("Lecture 1"), markedBy: text("marked_by"), createdAt: createdAt() });
export const grades = sqliteTable("grades", { id: id(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), courseId: integer("course_id").notNull(), courseName: text("course_name").notNull(), examType: text("exam_type").notNull(), marksObtained: text("marks_obtained").notNull(), maxMarks: text("max_marks").notNull().default("100"), gradeLetter: text("grade_letter").notNull(), semester: integer("semester").notNull().default(1), remarks: text("remarks"), createdAt: createdAt() });
export const feeRecords = sqliteTable("fee_records", { id: id(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), rollNo: text("roll_no").notNull(), feeType: text("fee_type").notNull(), amount: text("amount").notNull(), dueDate: text("due_date").notNull(), paidDate: text("paid_date"), status: text("status").notNull().default("pending"), receiptNumber: text("receipt_number"), paymentMethod: text("payment_method"), courseCode: text("course_code"), courseName: text("course_name"), semester: integer("semester"), paidAmount: text("paid_amount").notNull().default("0"), collectedBy: text("collected_by"), collectedAt: text("collected_at"), createdAt: createdAt() });
export const feeStructures = sqliteTable("fee_structures", { id: id(), courseCode: text("course_code").notNull(), courseName: text("course_name").notNull(), semester: integer("semester").notNull(), feeType: text("fee_type").notNull(), amount: text("amount").notNull(), dueDate: text("due_date").notNull(), createdAt: createdAt() });
export const feePayments = sqliteTable("fee_payments", { id: id(), feeRecordId: integer("fee_record_id").notNull(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), amount: text("amount").notNull(), paymentMethod: text("payment_method").notNull(), receiptNumber: text("receipt_number").notNull(), paidAt: text("paid_at").notNull(), collectedBy: text("collected_by"), collectedById: integer("collected_by_id"), createdAt: createdAt() });
export const assignments = sqliteTable("assignments", { id: id(), courseId: integer("course_id").notNull(), courseName: text("course_name").notNull(), title: text("title").notNull(), description: text("description").notNull(), dueDate: text("due_date").notNull(), maxMarks: integer("max_marks").notNull().default(100), facultyName: text("faculty_name").notNull(), createdAt: createdAt() });
export const assignmentSubmissions = sqliteTable("assignment_submissions", { id: id(), assignmentId: integer("assignment_id").notNull(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), submissionText: text("submission_text"), fileUrl: text("file_url"), status: text("status").notNull().default("submitted"), marks: text("marks"), feedback: text("feedback"), submittedAt: createdAt("submitted_at") });
export const notices = sqliteTable("notices", { id: id(), title: text("title").notNull(), content: text("content").notNull(), category: text("category").notNull().default("Academic"), priority: text("priority").notNull().default("normal"), authorName: text("author_name").notNull().default("Administration Office"), publishedDate: text("published_date").notNull(), createdAt: createdAt() });
export const leaveRequests = sqliteTable("leave_requests", { id: id(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), rollNo: text("roll_no").notNull(), department: text("department").notNull(), fromDate: text("from_date").notNull(), toDate: text("to_date").notNull(), reason: text("reason").notNull(), status: text("status").notNull().default("pending"), reviewedBy: text("reviewed_by"), reviewedAt: text("reviewed_at"), remarks: text("remarks"), createdAt: createdAt() });
export const timetable = sqliteTable("timetable", { id: id(), courseCode: text("course_code").notNull(), courseName: text("course_name").notNull(), department: text("department").notNull(), semester: integer("semester").notNull(), dayOfWeek: text("day_of_week").notNull(), startTime: text("start_time").notNull(), endTime: text("end_time").notNull(), room: text("room").notNull(), facultyName: text("faculty_name").notNull() });
export const admissions = sqliteTable("admissions", { id: id(), studentId: integer("student_id").notNull().unique(), admissionNumber: text("admission_number").notNull(), admissionDate: text("admission_date").notNull(), category: text("category").notNull().default("General"), previousInstitution: text("previous_institution"), fatherName: text("father_name"), motherName: text("mother_name"), guardianPhone: text("guardian_phone"), bloodGroup: text("blood_group"), address: text("address"), isHosteler: integer("is_hosteler").notNull().default(0), createdAt: createdAt() });
export const documents = sqliteTable("documents", { id: id(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), title: text("title").notNull(), category: text("category").notNull().default("Other"), fileName: text("file_name").notNull(), mimeType: text("mime_type").notNull().default("application/octet-stream"), fileSize: integer("file_size").notNull().default(0), data: text("data").notNull(), status: text("status").notNull().default("pending"), uploadedAt: createdAt("uploaded_at") });
export const enrollments = sqliteTable("enrollments", { id: id(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), courseId: integer("course_id").notNull(), courseCode: text("course_code").notNull(), courseName: text("course_name").notNull(), semester: integer("semester").notNull().default(1), status: text("status").notNull().default("active") });
export const sections = sqliteTable("sections", { id: id(), code: text("code").notNull(), name: text("name").notNull(), department: text("department").notNull(), semester: integer("semester").notNull().default(1), room: text("room") });
export const semesters = sqliteTable("semesters", { id: id(), number: integer("number").notNull(), name: text("name").notNull(), department: text("department").notNull(), status: text("status").notNull().default("inactive"), startsOn: text("starts_on"), endsOn: text("ends_on") });
export const academicSessions = sqliteTable("academic_sessions", { id: id(), name: text("name").notNull().unique(), startDate: text("start_date").notNull(), endDate: text("end_date").notNull(), isCurrent: integer("is_current").notNull().default(0) });
export const examSchedules = sqliteTable("exam_schedules", { id: id(), examType: text("exam_type").notNull(), courseCode: text("course_code").notNull(), courseName: text("course_name").notNull(), department: text("department").notNull(), semester: integer("semester").notNull().default(1), examDate: text("exam_date").notNull(), startTime: text("start_time").notNull(), endTime: text("end_time").notNull(), room: text("room").notNull() });
export const exams = sqliteTable("exams", { id: id(), name: text("name").notNull(), examType: text("exam_type").notNull().default("Mid-Term"), department: text("department").notNull(), semester: integer("semester").notNull().default(1), session: text("session").notNull().default("2025-26"), startDate: text("start_date").notNull(), endDate: text("end_date").notNull(), status: text("status").notNull().default("scheduled"), passingPercent: integer("passing_percent").notNull().default(40), createdAt: createdAt() });
export const internalMarks = sqliteTable("internal_marks", { id: id(), studentId: integer("student_id").notNull(), studentName: text("student_name").notNull(), courseId: integer("course_id").notNull(), courseCode: text("course_code").notNull(), courseName: text("course_name").notNull(), examType: text("exam_type").notNull(), semester: integer("semester").notNull().default(1), theoryMarks: text("theory_marks").notNull().default("0"), practicalMarks: text("practical_marks").notNull().default("0"), maxTheory: text("max_theory").notNull().default("30"), maxPractical: text("max_practical").notNull().default("20"), totalMarks: text("total_marks").notNull(), maxTotal: text("max_total").notNull(), passMarks: text("pass_marks").notNull(), gradeLetter: text("grade_letter").notNull(), result: text("result").notNull().default("pass"), status: text("status").notNull().default("draft"), remarks: text("remarks"), createdAt: createdAt() });
export const permissions = sqliteTable("permissions", { id: id(), role: text("role").notNull(), module: text("module").notNull(), canView: integer("can_view").notNull().default(1), canCreate: integer("can_create").notNull().default(0), canEdit: integer("can_edit").notNull().default(0), canDelete: integer("can_delete").notNull().default(0) });
export const facultyAttendance = sqliteTable("faculty_attendance", { id: id(), facultyId: integer("faculty_id").notNull(), facultyName: text("faculty_name").notNull(), date: text("date").notNull(), status: text("status").notNull().default("present"), markedBy: text("marked_by"), createdAt: createdAt() });
export const courseMaterials = sqliteTable("course_materials", { id: id(), courseId: integer("course_id").notNull(), courseCode: text("course_code").notNull(), courseName: text("course_name").notNull(), moduleName: text("module_name").notNull(), title: text("title").notNull(), description: text("description"), type: text("type").notNull().default("PDF"), fileUrl: text("file_url").notNull(), fileSize: text("file_size").notNull().default("1.5 MB"), facultyId: integer("faculty_id"), facultyName: text("faculty_name").notNull(), downloadCount: integer("download_count").notNull().default(0), createdAt: createdAt() });
