namespace VscmsErp.Api.Data;

/// <summary>
/// Idempotent Postgres schema statements (mirror of src/db/schema.ts).
/// Used by EnsureDatabase() so the API can create its tables on a fresh
/// database. Note: created_at stays TEXT with a SQLite-style default string
/// ("YYYY-MM-DD HH:MM:SS") so row readers that cast it to string keep working.
/// </summary>
public static class Schema
{
    public static readonly string[] DDL =
    [
        """
        CREATE TABLE IF NOT EXISTS "users" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "name" TEXT NOT NULL,
          "email" TEXT NOT NULL UNIQUE,
          "role" TEXT NOT NULL DEFAULT 'student',
          "roll_no_or_emp_id" TEXT NOT NULL,
          "department" TEXT NOT NULL,
          "semester" BIGINT,
          "designation" TEXT,
          "phone" TEXT,
          "avatar_url" TEXT,
          "gpa" TEXT,
          "status" TEXT NOT NULL DEFAULT 'active',
          "password_hash" TEXT NOT NULL DEFAULT '',
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "sessions" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "token" TEXT NOT NULL UNIQUE,
          "user_id" BIGINT NOT NULL,
          "expires_at" BIGINT NOT NULL,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "departments" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "code" TEXT NOT NULL UNIQUE,
          "name" TEXT NOT NULL,
          "head_of_department" TEXT NOT NULL,
          "location" TEXT,
          "student_count" BIGINT DEFAULT 0,
          "faculty_count" BIGINT DEFAULT 0
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "courses" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "code" TEXT NOT NULL UNIQUE,
          "name" TEXT NOT NULL,
          "department" TEXT NOT NULL,
          "credits" BIGINT NOT NULL DEFAULT 3,
          "semester" BIGINT NOT NULL DEFAULT 1,
          "faculty_id" BIGINT,
          "faculty_name" TEXT,
          "room" TEXT,
          "schedule" TEXT,
          "description" TEXT
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "attendance" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "course_id" BIGINT NOT NULL,
          "course_code" TEXT NOT NULL,
          "date" TEXT NOT NULL,
          "status" TEXT NOT NULL,
          "period" TEXT DEFAULT 'Lecture 1',
          "marked_by" TEXT,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "grades" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "course_id" BIGINT NOT NULL,
          "course_name" TEXT NOT NULL,
          "exam_type" TEXT NOT NULL,
          "marks_obtained" TEXT NOT NULL,
          "max_marks" TEXT NOT NULL DEFAULT '100',
          "grade_letter" TEXT NOT NULL,
          "semester" BIGINT NOT NULL DEFAULT 1,
          "remarks" TEXT,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "fee_records" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "roll_no" TEXT NOT NULL,
          "fee_type" TEXT NOT NULL,
          "amount" TEXT NOT NULL,
          "due_date" TEXT NOT NULL,
          "paid_date" TEXT,
          "status" TEXT NOT NULL DEFAULT 'pending',
          "receipt_number" TEXT,
          "payment_method" TEXT,
          "course_code" TEXT,
          "course_name" TEXT,
          "semester" BIGINT,
          "paid_amount" TEXT NOT NULL DEFAULT '0',
          "collected_by" TEXT,
          "collected_at" TEXT,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "fee_structures" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "course_code" TEXT NOT NULL,
          "course_name" TEXT NOT NULL,
          "semester" BIGINT NOT NULL,
          "fee_type" TEXT NOT NULL,
          "amount" TEXT NOT NULL,
          "due_date" TEXT NOT NULL,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "fee_payments" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "fee_record_id" BIGINT NOT NULL,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "amount" TEXT NOT NULL,
          "payment_method" TEXT NOT NULL,
          "receipt_number" TEXT NOT NULL,
          "paid_at" TEXT NOT NULL,
          "collected_by" TEXT,
          "collected_by_id" BIGINT,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "assignments" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "course_id" BIGINT NOT NULL,
          "course_name" TEXT NOT NULL,
          "title" TEXT NOT NULL,
          "description" TEXT NOT NULL,
          "due_date" TEXT NOT NULL,
          "max_marks" BIGINT NOT NULL DEFAULT 100,
          "faculty_name" TEXT NOT NULL,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "assignment_submissions" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "assignment_id" BIGINT NOT NULL,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "submission_text" TEXT,
          "file_url" TEXT,
          "status" TEXT NOT NULL DEFAULT 'submitted',
          "marks" TEXT,
          "feedback" TEXT,
          "submitted_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "notices" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "title" TEXT NOT NULL,
          "content" TEXT NOT NULL,
          "category" TEXT NOT NULL DEFAULT 'Academic',
          "priority" TEXT NOT NULL DEFAULT 'normal',
          "author_name" TEXT NOT NULL DEFAULT 'Administration Office',
          "published_date" TEXT NOT NULL,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "leave_requests" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "roll_no" TEXT NOT NULL,
          "department" TEXT NOT NULL,
          "from_date" TEXT NOT NULL,
          "to_date" TEXT NOT NULL,
          "reason" TEXT NOT NULL,
          "status" TEXT NOT NULL DEFAULT 'pending',
          "reviewed_by" TEXT,
          "reviewed_at" TEXT,
          "remarks" TEXT,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "timetable" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "course_code" TEXT NOT NULL,
          "course_name" TEXT NOT NULL,
          "department" TEXT NOT NULL,
          "semester" BIGINT NOT NULL,
          "day_of_week" TEXT NOT NULL,
          "start_time" TEXT NOT NULL,
          "end_time" TEXT NOT NULL,
          "room" TEXT NOT NULL,
          "faculty_name" TEXT NOT NULL
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "admissions" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "student_id" BIGINT NOT NULL UNIQUE,
          "admission_number" TEXT NOT NULL,
          "admission_date" TEXT NOT NULL,
          "category" TEXT NOT NULL DEFAULT 'General',
          "previous_institution" TEXT,
          "father_name" TEXT,
          "mother_name" TEXT,
          "guardian_phone" TEXT,
          "blood_group" TEXT,
          "address" TEXT,
          "is_hosteler" BIGINT NOT NULL DEFAULT 0,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "documents" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "title" TEXT NOT NULL,
          "category" TEXT NOT NULL DEFAULT 'Other',
          "file_name" TEXT NOT NULL,
          "mime_type" TEXT NOT NULL DEFAULT 'application/octet-stream',
          "file_size" BIGINT NOT NULL DEFAULT 0,
          "data" TEXT NOT NULL,
          "status" TEXT NOT NULL DEFAULT 'pending',
          "uploaded_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "enrollments" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "course_id" BIGINT NOT NULL,
          "course_code" TEXT NOT NULL,
          "course_name" TEXT NOT NULL,
          "semester" BIGINT NOT NULL DEFAULT 1,
          "status" TEXT NOT NULL DEFAULT 'active'
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "sections" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "code" TEXT NOT NULL,
          "name" TEXT NOT NULL,
          "department" TEXT NOT NULL,
          "semester" BIGINT NOT NULL DEFAULT 1,
          "room" TEXT
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "semesters" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "number" BIGINT NOT NULL,
          "name" TEXT NOT NULL,
          "department" TEXT NOT NULL,
          "status" TEXT NOT NULL DEFAULT 'inactive',
          "starts_on" TEXT,
          "ends_on" TEXT
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "academic_sessions" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "name" TEXT NOT NULL UNIQUE,
          "start_date" TEXT NOT NULL,
          "end_date" TEXT NOT NULL,
          "is_current" BIGINT NOT NULL DEFAULT 0
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "exam_schedules" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "exam_type" TEXT NOT NULL,
          "course_code" TEXT NOT NULL,
          "course_name" TEXT NOT NULL,
          "department" TEXT NOT NULL,
          "semester" BIGINT NOT NULL DEFAULT 1,
          "exam_date" TEXT NOT NULL,
          "start_time" TEXT NOT NULL,
          "end_time" TEXT NOT NULL,
          "room" TEXT NOT NULL
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "exams" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "name" TEXT NOT NULL,
          "exam_type" TEXT NOT NULL DEFAULT 'Mid-Term',
          "department" TEXT NOT NULL,
          "semester" BIGINT NOT NULL DEFAULT 1,
          "session" TEXT NOT NULL DEFAULT '2025-26',
          "start_date" TEXT NOT NULL,
          "end_date" TEXT NOT NULL,
          "status" TEXT NOT NULL DEFAULT 'scheduled',
          "passing_percent" BIGINT NOT NULL DEFAULT 40,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "internal_marks" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "student_id" BIGINT NOT NULL,
          "student_name" TEXT NOT NULL,
          "course_id" BIGINT NOT NULL,
          "course_code" TEXT NOT NULL,
          "course_name" TEXT NOT NULL,
          "exam_type" TEXT NOT NULL,
          "semester" BIGINT NOT NULL DEFAULT 1,
          "theory_marks" TEXT NOT NULL DEFAULT '0',
          "practical_marks" TEXT NOT NULL DEFAULT '0',
          "max_theory" TEXT NOT NULL DEFAULT '30',
          "max_practical" TEXT NOT NULL DEFAULT '20',
          "total_marks" TEXT NOT NULL,
          "max_total" TEXT NOT NULL,
          "pass_marks" TEXT NOT NULL,
          "grade_letter" TEXT NOT NULL,
          "result" TEXT NOT NULL DEFAULT 'pass',
          "status" TEXT NOT NULL DEFAULT 'draft',
          "remarks" TEXT,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "permissions" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "role" TEXT NOT NULL,
          "module" TEXT NOT NULL,
          "can_view" BIGINT NOT NULL DEFAULT 1,
          "can_create" BIGINT NOT NULL DEFAULT 0,
          "can_edit" BIGINT NOT NULL DEFAULT 0,
          "can_delete" BIGINT NOT NULL DEFAULT 0
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "faculty_attendance" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "faculty_id" BIGINT NOT NULL,
          "faculty_name" TEXT NOT NULL,
          "date" TEXT NOT NULL,
          "status" TEXT NOT NULL DEFAULT 'present',
          "marked_by" TEXT,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
        """
        CREATE TABLE IF NOT EXISTS "course_materials" (
          "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          "course_id" BIGINT NOT NULL,
          "course_code" TEXT NOT NULL,
          "course_name" TEXT NOT NULL,
          "module_name" TEXT NOT NULL,
          "title" TEXT NOT NULL,
          "description" TEXT,
          "type" TEXT NOT NULL DEFAULT 'PDF',
          "file_url" TEXT NOT NULL,
          "file_size" TEXT NOT NULL DEFAULT '1.5 MB',
          "faculty_id" BIGINT,
          "faculty_name" TEXT NOT NULL,
          "download_count" BIGINT NOT NULL DEFAULT 0,
          "created_at" TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH:MM:SS')
        );
        """,
    ];
}
